spring:
  datasource:
    url: jdbc:h2:file:~/assetvulndb;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    cache: false

  http:
    codecs:
      max-in-memory-size: 2MB

logging:
  level:
    org.hibernate.SQL: debug
    dev.notegridx.security.assetvulnmanager: info
    
app:

  software:
    dict-mode: STRICT  # or LENIENT

  nvd:
    base-url: https://services.nvd.nist.gov
    api-key: ${NVD_API_KEY:}

    cpe:
      base-url: https://nvd.nist.gov
      meta-path: /feeds/json/cpe/2.0/nvdcpe-2.0.meta
      gz-path: /feeds/json/cpe/2.0/nvdcpe-2.0.tar.gz

    software:
      dict-mode: STRICT  # or LENIENT
