spring:
  profiles:
    default: h2

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2MB

  http:
    codecs:
      max-in-memory-size: 2MB

logging:
  level:
    org.hibernate.SQL: info
    dev.notegridx.security.assetvulnmanager: info
    dev.notegridx.security.assetvulnmanager.service.CanonicalCpeLinkingService: info
    dev.notegridx.security.assetvulnmanager.service.TokenMatchingService: info
    dev.notegridx.security.assetvulnmanager.service.MatchingService: info
    dev.notegridx.security.assetvulnmanager.service.CriteriaEvaluator: info

app:

  software:
    dict-mode: STRICT

  import:
    session-ttl-minutes: 30
    session-dir:

  nvd:
    base-url: https://services.nvd.nist.gov
    api-key: ${NVD_API_KEY:}

    cpe:
      base-url: https://nvd.nist.gov
      meta-path: /feeds/json/cpe/2.0/nvdcpe-2.0.meta
      gz-path: /feeds/json/cpe/2.0/nvdcpe-2.0.tar.gz

      meta-timeout-seconds: 60
      download-timeout-minutes: 20
      connect-timeout-millis: 30000
      response-timeout-seconds: 120
      max-retries: 3

    cve:
      base-url: https://nvd.nist.gov

      modified:
        meta-path: /feeds/json/cve/2.0/nvdcve-2.0-modified.meta
        gz-path: /feeds/json/cve/2.0/nvdcve-2.0-modified.json.gz

      recent:
        meta-path: /feeds/json/cve/2.0/nvdcve-2.0-recent.meta
        gz-path: /feeds/json/cve/2.0/nvdcve-2.0-recent.json.gz

      year:
        meta-path-pattern: /feeds/json/cve/2.0/nvdcve-2.0-{year}.meta
        gz-path-pattern: /feeds/json/cve/2.0/nvdcve-2.0-{year}.json.gz

    software:
      dict-mode: STRICT