-- =========================================================
-- schema.sql (H2) - Normal use (IF NOT EXISTS)
-- The database is typically persisted; drop tables manually when reset is required.
-- =========================================================

-- =========================================================
-- Assets
-- =========================================================

CREATE TABLE IF NOT EXISTS assets
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key VARCHAR(128),
    name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(32),
    owner VARCHAR(255),
    note CLOB,

    -- Inventory ingestion source (e.g., osquery / fleet / wazuh / manual)
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',

    -- Optional platform hint (e.g., windows / linux / darwin)
    platform VARCHAR(32),

    -- Optional OS display hint (free-form string)
    os_version VARCHAR(128),

    -- Identity / hardware / OS details (designed for osquery compatibility)
    system_uuid VARCHAR(128),
    serial_number VARCHAR(128),

    hardware_vendor VARCHAR(255),
    hardware_model VARCHAR(255),
    hardware_version VARCHAR(255),

    computer_name VARCHAR(255),
    local_hostname VARCHAR(255),
    hostname VARCHAR(255),

    cpu_brand VARCHAR(255),
    cpu_physical_cores INT,
    cpu_logical_cores INT,
    cpu_sockets INT,
    physical_memory BIGINT,
    arch VARCHAR(64),

    board_vendor VARCHAR(255),
    board_model VARCHAR(255),
    board_version VARCHAR(255),
    board_serial VARCHAR(255),

    os_name VARCHAR(128),
    os_build VARCHAR(128),
    os_major INT,
    os_minor INT,
    os_patch INT,

    -- Timestamp of the latest observation (snapshot-based inventory)
    last_seen_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_assets_external_key UNIQUE (external_key)
    );

-- NOTE:
-- uq_assets_external_key already creates an index.
-- idx_assets_external_key is usually redundant, but retained for backward compatibility.
-- Keep or remove based on operational policy.
CREATE INDEX IF NOT EXISTS idx_assets_external_key ON assets(external_key);
CREATE INDEX IF NOT EXISTS idx_assets_source ON assets(source);
CREATE INDEX IF NOT EXISTS idx_assets_last_seen ON assets(last_seen_at);

-- Additional indexes (optional but useful for lookup and correlation)
CREATE INDEX IF NOT EXISTS idx_assets_system_uuid ON assets(system_uuid);
CREATE INDEX IF NOT EXISTS idx_assets_serial_number ON assets(serial_number);
CREATE INDEX IF NOT EXISTS idx_assets_local_hostname ON assets(local_hostname);
CREATE INDEX IF NOT EXISTS idx_assets_platform ON assets(platform);

-- =========================================================
-- CPE Dictionary (vendors/products)
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_vendors
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_norm VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),

    -- Data origin (default: official CPE dictionary)
    source VARCHAR(20) NOT NULL DEFAULT 'CPE_DICT',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_cpe_vendors_name UNIQUE (name_norm)
    );

-- Index to support normalized vendor lookup
CREATE INDEX IF NOT EXISTS idx_cpe_vendors_name ON cpe_vendors(name_norm);

CREATE TABLE IF NOT EXISTS cpe_products
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Foreign key to vendor
    vendor_id BIGINT NOT NULL,

    name_norm VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),

    -- Data origin (default: official CPE dictionary)
    source VARCHAR(20) NOT NULL DEFAULT 'CPE_DICT',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_cpe_products_vendor FOREIGN KEY (vendor_id) REFERENCES cpe_vendors(id),

    -- Unique constraint within vendor scope
    CONSTRAINT uq_cpe_products_vendor_name UNIQUE (vendor_id, name_norm)
    );

-- Indexes to support vendor/product resolution and search
CREATE INDEX IF NOT EXISTS idx_cpe_products_vendor ON cpe_products(vendor_id);
CREATE INDEX IF NOT EXISTS idx_cpe_products_name ON cpe_products(name_norm);
CREATE INDEX IF NOT EXISTS idx_cpe_products_vendor_name ON cpe_products(vendor_id, name_norm);

-- =========================================================
-- CPE Feed sync state
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Feed identifier (e.g., official dictionary feed name)
    feed_name VARCHAR(64) NOT NULL,

    meta_sha256 VARCHAR(128),
    meta_last_modified VARCHAR(64),
    meta_size BIGINT,

    last_synced_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_cpe_sync_state_feed UNIQUE (feed_name)
    );

-- Fast lookup by feed name
CREATE INDEX IF NOT EXISTS idx_cpe_sync_state_feed ON cpe_sync_state(feed_name);

-- =========================================================
-- Import runs (inventory ingestion unit)
-- =========================================================

CREATE TABLE IF NOT EXISTS import_runs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Core ingestion metadata
    source VARCHAR(32) NOT NULL,
    kind VARCHAR(32) NOT NULL,

    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,

    file_hash VARCHAR(128),
    summary CLOB,

    -- Counters for ingestion results
    assets_upserted INT DEFAULT 0 NOT NULL,
    software_upserted INT DEFAULT 0 NOT NULL,
    unresolved_count INT DEFAULT 0 NOT NULL,
    error_count INT DEFAULT 0 NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Extended metadata for UI / audit / troubleshooting
    status VARCHAR(16) NOT NULL DEFAULT 'IMPORTED',
    original_filename VARCHAR(255),
    sha256 VARCHAR(128),

    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    invalid_rows INT NOT NULL DEFAULT 0,

    error_message VARCHAR(1024),

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

-- Indexes for run history filtering and sorting
CREATE INDEX IF NOT EXISTS idx_import_runs_started ON import_runs(started_at);
CREATE INDEX IF NOT EXISTS idx_import_runs_source ON import_runs(source);
CREATE INDEX IF NOT EXISTS idx_import_runs_status ON import_runs(status);

-- =========================================================
-- Admin Runs (generic job execution history)
-- =========================================================

CREATE TABLE IF NOT EXISTS admin_runs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Job metadata
    job_type VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,

    started_at TIMESTAMP(6) NOT NULL,
    finished_at TIMESTAMP(6),
    duration_ms BIGINT,

    params_json CLOB,
    result_json CLOB,
    error_message CLOB,

    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
    );

-- Indexes for operational monitoring and filtering
CREATE INDEX IF NOT EXISTS idx_admin_runs_started_at ON admin_runs (started_at);
CREATE INDEX IF NOT EXISTS idx_admin_runs_job_type   ON admin_runs (job_type);
CREATE INDEX IF NOT EXISTS idx_admin_runs_status     ON admin_runs (status);

-- =========================================================
-- Software inventory
-- =========================================================

CREATE TABLE IF NOT EXISTS software_installs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,

    type VARCHAR(32) NOT NULL DEFAULT 'APPLICATION',
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',

    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255),
    version_raw VARCHAR(128),

    vendor VARCHAR(255) NOT NULL DEFAULT '',
    product VARCHAR(255) NOT NULL,

    version VARCHAR(64) NOT NULL DEFAULT '',
    version_norm VARCHAR(128),

    cpe_name VARCHAR(512),

    normalized_vendor VARCHAR(255),
    normalized_product VARCHAR(255),

    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    last_seen_at TIMESTAMP,

    import_run_id BIGINT,

    install_location VARCHAR(1024),
    installed_at TIMESTAMP NULL,
    package_identifier VARCHAR(255),
    arch VARCHAR(64),

    source_type VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',

    publisher VARCHAR(255),
    bundle_id VARCHAR(255),
    package_manager VARCHAR(64),
    install_source VARCHAR(64),

    edition VARCHAR(128),
    channel VARCHAR(64),
    release_label VARCHAR(128),

    purl VARCHAR(512),

    canonical_link_disabled BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_sw_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT fk_sw_cpe_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_sw_cpe_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id),
    CONSTRAINT fk_sw_import_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id),

    CONSTRAINT uq_sw_asset_vendor_product_version UNIQUE (asset_id, vendor, product, version)
    );

CREATE INDEX IF NOT EXISTS idx_sw_asset_id ON software_installs(asset_id);
CREATE INDEX IF NOT EXISTS idx_sw_cpe ON software_installs(cpe_name);
CREATE INDEX IF NOT EXISTS idx_sw_norm ON software_installs(normalized_vendor, normalized_product);
CREATE INDEX IF NOT EXISTS idx_sw_type ON software_installs(type);
CREATE INDEX IF NOT EXISTS idx_sw_source ON software_installs(source);
CREATE INDEX IF NOT EXISTS idx_sw_source_type ON software_installs(source_type);
CREATE INDEX IF NOT EXISTS idx_sw_last_seen ON software_installs(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_sw_import_run ON software_installs(import_run_id);

-- Additional indexes (safe)
CREATE INDEX IF NOT EXISTS idx_sw_pkg_identifier ON software_installs(package_identifier);
CREATE INDEX IF NOT EXISTS idx_sw_publisher ON software_installs(publisher);
CREATE INDEX IF NOT EXISTS idx_sw_bundle_id ON software_installs(bundle_id);
CREATE INDEX IF NOT EXISTS idx_sw_pkg_manager ON software_installs(package_manager);
CREATE INDEX IF NOT EXISTS idx_sw_purl ON software_installs(purl);

-- Matching accelerators (DICT_ID is the primary path)
CREATE INDEX IF NOT EXISTS idx_sw_vendor_product_id
    ON software_installs(cpe_vendor_id, cpe_product_id);

CREATE INDEX IF NOT EXISTS idx_sw_asset_vendor_product_id
    ON software_installs(asset_id, cpe_vendor_id, cpe_product_id);

-- =========================================================
-- Staging tables for JSON import (Upload -> Preview -> Import)
-- =========================================================

CREATE TABLE IF NOT EXISTS import_staging_assets
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_run_id BIGINT NOT NULL,
    row_no INT NOT NULL,

    external_key VARCHAR(128),
    name VARCHAR(255),
    asset_type VARCHAR(32),
    owner VARCHAR(255),
    note CLOB,

    source VARCHAR(32),
    platform VARCHAR(32),
    os_version VARCHAR(128),

    system_uuid VARCHAR(128),
    serial_number VARCHAR(128),

    hardware_vendor VARCHAR(255),
    hardware_model VARCHAR(255),
    hardware_version VARCHAR(255),

    computer_name VARCHAR(255),
    local_hostname VARCHAR(255),
    hostname VARCHAR(255),

    cpu_brand VARCHAR(255),
    cpu_physical_cores INT,
    cpu_logical_cores INT,
    cpu_sockets INT,
    physical_memory BIGINT,
    arch VARCHAR(64),

    board_vendor VARCHAR(255),
    board_model VARCHAR(255),
    board_version VARCHAR(255),
    board_serial VARCHAR(255),

    os_name VARCHAR(128),
    os_build VARCHAR(128),
    os_major INT,
    os_minor INT,
    os_patch INT,

    last_seen_at TIMESTAMP,

    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    validation_error VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_stage_assets_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id)
    );

CREATE INDEX IF NOT EXISTS idx_stage_assets_run ON import_staging_assets(import_run_id);
CREATE INDEX IF NOT EXISTS idx_stage_assets_key ON import_staging_assets(external_key);

CREATE TABLE IF NOT EXISTS import_staging_software
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_run_id BIGINT NOT NULL,
    row_no INT NOT NULL,

    external_key VARCHAR(128),

    vendor VARCHAR(255),
    product VARCHAR(255),
    version VARCHAR(64),

    install_location VARCHAR(1024),
    installed_at TIMESTAMP NULL,
    package_identifier VARCHAR(255),
    arch VARCHAR(64),

    source_type VARCHAR(64) NOT NULL DEFAULT 'JSON_UPLOAD',

    last_seen_at TIMESTAMP,

    type VARCHAR(32),
    source VARCHAR(32),

    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255),
    version_raw VARCHAR(128),

    publisher VARCHAR(255),
    bundle_id VARCHAR(255),
    package_manager VARCHAR(64),
    install_source VARCHAR(64),

    edition VARCHAR(128),
    channel VARCHAR(64),
    release_label VARCHAR(128),

    purl VARCHAR(512),

    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    validation_error VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_stage_sw_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id)
    );

CREATE INDEX IF NOT EXISTS idx_stage_sw_run ON import_staging_software(import_run_id);
CREATE INDEX IF NOT EXISTS idx_stage_sw_key ON import_staging_software(external_key);
CREATE INDEX IF NOT EXISTS idx_stage_sw_product ON import_staging_software(product);

-- =========================================================
-- Vulnerabilities (CVE)
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerabilities
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source VARCHAR(32) NOT NULL DEFAULT 'NVD',
    external_id VARCHAR(64) NOT NULL,

    description CLOB,

    severity VARCHAR(16),
    cvss_version VARCHAR(16),
    cvss_score DOUBLE,

    published_at TIMESTAMP,
    last_modified_at TIMESTAMP,

    -- ==============================
    -- KEV metadata
    -- ==============================
    kev_flag BOOLEAN DEFAULT FALSE NOT NULL,
    kev_date_added DATE,
    kev_due_date DATE,
    kev_ransomware_use VARCHAR(16),
    kev_updated_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_vuln_source_external UNIQUE (source, external_id)
    );

CREATE INDEX IF NOT EXISTS idx_vuln_severity ON vulnerabilities(severity);
CREATE INDEX IF NOT EXISTS idx_vuln_lastmod_id ON vulnerabilities(last_modified_at, id);
CREATE INDEX IF NOT EXISTS idx_vuln_kev_flag ON vulnerabilities(kev_flag);

-- =========================================================
-- KEV sync state
-- =========================================================
CREATE TABLE IF NOT EXISTS kev_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    feed_name VARCHAR(64) NOT NULL,
    etag VARCHAR(255),
    last_modified VARCHAR(128),
    body_sha256 VARCHAR(128),
    body_size BIGINT,
    fetched_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_kev_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_kev_sync_state_feed ON kev_sync_state(feed_name);

-- =========================================================
-- Vulnerability affected CPEs
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerability_affected_cpes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vulnerability_id BIGINT NOT NULL,

    cpe_name VARCHAR(512) NOT NULL,

    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    vendor_norm VARCHAR(255),
    product_norm VARCHAR(255),

    cpe_part VARCHAR(8),
    target_sw VARCHAR(64),
    target_hw VARCHAR(64),

    version_start_including VARCHAR(255) NOT NULL DEFAULT '',
    version_start_excluding VARCHAR(255) NOT NULL DEFAULT '',
    version_end_including   VARCHAR(255) NOT NULL DEFAULT '',
    version_end_excluding   VARCHAR(255) NOT NULL DEFAULT '',

    criteria_node_id BIGINT,
    root_group_no INT NOT NULL DEFAULT 0,

    dedupe_key CHAR(64),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vac_vuln
    FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),

    CONSTRAINT fk_vac_cpe_vendor
    FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),

    CONSTRAINT fk_vac_cpe_product
    FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id)
    );

CREATE INDEX IF NOT EXISTS idx_vac_cpe ON vulnerability_affected_cpes(cpe_name);
CREATE INDEX IF NOT EXISTS idx_vac_vuln ON vulnerability_affected_cpes(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_id ON vulnerability_affected_cpes(cpe_vendor_id, cpe_product_id);
CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_norm ON vulnerability_affected_cpes(vendor_norm, product_norm);
CREATE INDEX IF NOT EXISTS idx_vac_target_sw ON vulnerability_affected_cpes(target_sw);
CREATE INDEX IF NOT EXISTS idx_vac_criteria_node ON vulnerability_affected_cpes(criteria_node_id);
CREATE INDEX IF NOT EXISTS idx_vac_vuln_root ON vulnerability_affected_cpes(vulnerability_id, root_group_no);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vac_dedupe_key ON vulnerability_affected_cpes(dedupe_key);

-- =========================================================
-- Vulnerability criteria tree
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerability_criteria_nodes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vulnerability_id BIGINT NOT NULL,
    parent_id BIGINT,

    root_group_no INT NOT NULL DEFAULT 0,
    node_type VARCHAR(16) NOT NULL,
    operator VARCHAR(8),
    negate BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vcn_vuln
    FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),

    CONSTRAINT fk_vcn_parent
    FOREIGN KEY (parent_id) REFERENCES vulnerability_criteria_nodes(id)
    );

CREATE INDEX IF NOT EXISTS idx_vcn_vuln_root ON vulnerability_criteria_nodes(vulnerability_id, root_group_no);
CREATE INDEX IF NOT EXISTS idx_vcn_parent ON vulnerability_criteria_nodes(parent_id);
CREATE INDEX IF NOT EXISTS idx_vcn_vuln_type ON vulnerability_criteria_nodes(vulnerability_id, node_type);

CREATE TABLE IF NOT EXISTS vulnerability_criteria_cpes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    node_id BIGINT NOT NULL,
    vulnerability_id BIGINT NOT NULL,

    cpe_name VARCHAR(512) NOT NULL,

    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    vendor_norm VARCHAR(255),
    product_norm VARCHAR(255),

    cpe_part VARCHAR(8),
    target_sw VARCHAR(64),
    target_hw VARCHAR(64),

    version_start_including VARCHAR(255) NOT NULL DEFAULT '',
    version_start_excluding VARCHAR(255) NOT NULL DEFAULT '',
    version_end_including   VARCHAR(255) NOT NULL DEFAULT '',
    version_end_excluding   VARCHAR(255) NOT NULL DEFAULT '',

    match_vulnerable BOOLEAN NOT NULL DEFAULT TRUE,
    dedupe_key CHAR(64),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vcc_node
    FOREIGN KEY (node_id) REFERENCES vulnerability_criteria_nodes(id),

    CONSTRAINT fk_vcc_vuln
    FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),

    CONSTRAINT fk_vcc_vendor
    FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),

    CONSTRAINT fk_vcc_product
    FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id)
    );

CREATE INDEX IF NOT EXISTS idx_vcc_vuln ON vulnerability_criteria_cpes(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_vcc_node ON vulnerability_criteria_cpes(node_id);
CREATE INDEX IF NOT EXISTS idx_vcc_vendor_product_id ON vulnerability_criteria_cpes(cpe_vendor_id, cpe_product_id);
CREATE INDEX IF NOT EXISTS idx_vcc_vendor_product_norm ON vulnerability_criteria_cpes(vendor_norm, product_norm);
CREATE INDEX IF NOT EXISTS idx_vcc_cpe_name ON vulnerability_criteria_cpes(cpe_name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vcc_dedupe_key ON vulnerability_criteria_cpes(dedupe_key);

-- =========================================================
-- Alerts
-- =========================================================

CREATE TABLE IF NOT EXISTS alerts
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    software_install_id BIGINT,
    vulnerability_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL,
    certainty VARCHAR(16) NOT NULL DEFAULT 'CONFIRMED',
    uncertain_reason VARCHAR(64),
    matched_by VARCHAR(32),

    close_reason VARCHAR(255),
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,

    snapshot_asset_id BIGINT,
    snapshot_asset_name VARCHAR(255),
    snapshot_external_key VARCHAR(128),
    snapshot_software_install_id BIGINT,
    snapshot_vendor VARCHAR(255),
    snapshot_product VARCHAR(255),
    snapshot_version VARCHAR(64),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_alert_sw FOREIGN KEY (software_install_id) REFERENCES software_installs(id),
    CONSTRAINT fk_alert_vuln FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),
    CONSTRAINT uq_alert_pair UNIQUE (software_install_id, vulnerability_id)
    );

CREATE INDEX IF NOT EXISTS idx_alert_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alert_certainty ON alerts(certainty);
CREATE INDEX IF NOT EXISTS idx_alert_vuln ON alerts(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_alert_sw ON alerts(software_install_id);
CREATE INDEX IF NOT EXISTS idx_alert_status_certainty ON alerts(status, certainty);
CREATE INDEX IF NOT EXISTS idx_alert_vuln_status ON alerts(vulnerability_id, status);

-- =========================================================
-- CVE feed sync state (NVD CVE JSON 2.0 feeds)
-- =========================================================

CREATE TABLE IF NOT EXISTS cve_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    feed_name VARCHAR(64) NOT NULL,

    meta_sha256 VARCHAR(128),
    meta_last_modified VARCHAR(64),
    meta_size BIGINT,

    last_synced_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_cve_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_cve_sync_state_feed ON cve_sync_state(feed_name);

-- =========================================================
-- Unresolved mappings (dictionary training queue)
-- =========================================================

CREATE TABLE IF NOT EXISTS unresolved_mappings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source VARCHAR(32) NOT NULL,

    vendor_raw VARCHAR(255) NOT NULL,
    product_raw VARCHAR(255) NOT NULL,
    version_raw VARCHAR(128),

    normalized_vendor VARCHAR(255),
    normalized_product VARCHAR(255),

    candidate_vendor_ids VARCHAR(512),
    candidate_product_ids VARCHAR(512),

    status VARCHAR(16) NOT NULL DEFAULT 'NEW',
    note VARCHAR(1024),

    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    linked_cpe_vendor_id BIGINT,
    linked_cpe_product_id BIGINT,
    linked_vendor_name VARCHAR(255),
    linked_product_name VARCHAR(255),

    CONSTRAINT uk_um_vendor_product UNIQUE (vendor_raw, product_raw)
    );

CREATE INDEX IF NOT EXISTS idx_um_status ON unresolved_mappings(status);
CREATE INDEX IF NOT EXISTS idx_um_norm ON unresolved_mappings(normalized_vendor, normalized_product);
CREATE INDEX IF NOT EXISTS idx_um_vendor_product ON unresolved_mappings(vendor_raw, product_raw);

-- =========================================================
-- Synonyms / aliases (dictionary learning) [ID-based]
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_vendor_aliases
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    alias_norm VARCHAR(255) NOT NULL,

    cpe_vendor_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    note VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_vendor_alias_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT uq_vendor_alias UNIQUE (alias_norm)
    );

CREATE INDEX IF NOT EXISTS idx_vendor_alias_vendor ON cpe_vendor_aliases(cpe_vendor_id);
CREATE INDEX IF NOT EXISTS idx_vendor_alias_status ON cpe_vendor_aliases(status);

CREATE TABLE IF NOT EXISTS cpe_product_aliases
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cpe_vendor_id BIGINT NOT NULL,

    alias_norm VARCHAR(255) NOT NULL,

    cpe_product_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    note VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_product_alias_vendor  FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_product_alias_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id),
    CONSTRAINT uq_product_alias UNIQUE (cpe_vendor_id, alias_norm)
    );

CREATE INDEX IF NOT EXISTS idx_product_alias_vendor ON cpe_product_aliases(cpe_vendor_id);
CREATE INDEX IF NOT EXISTS idx_product_alias_product ON cpe_product_aliases(cpe_product_id);
CREATE INDEX IF NOT EXISTS idx_product_alias_status ON cpe_product_aliases(status);

-- =========================================================
-- Alias metadata extension (Top20 auto-seeding)
-- =========================================================

-- ---------- cpe_vendor_aliases ----------
ALTER TABLE cpe_vendor_aliases
    ADD COLUMN IF NOT EXISTS source VARCHAR(32) NOT NULL DEFAULT 'MANUAL';

ALTER TABLE cpe_vendor_aliases
    ADD COLUMN IF NOT EXISTS confidence INT NOT NULL DEFAULT 0;

ALTER TABLE cpe_vendor_aliases
    ADD COLUMN IF NOT EXISTS evidence_url VARCHAR(1024);

ALTER TABLE cpe_vendor_aliases
    ADD COLUMN IF NOT EXISTS review_state VARCHAR(16) NOT NULL DEFAULT 'MANUAL';

CREATE INDEX IF NOT EXISTS idx_cpe_vendor_aliases_review_state ON cpe_vendor_aliases(review_state);
CREATE INDEX IF NOT EXISTS idx_cpe_vendor_aliases_source       ON cpe_vendor_aliases(source);

-- ---------- cpe_product_aliases ----------
ALTER TABLE cpe_product_aliases
    ADD COLUMN IF NOT EXISTS source VARCHAR(32) NOT NULL DEFAULT 'MANUAL';

ALTER TABLE cpe_product_aliases
    ADD COLUMN IF NOT EXISTS confidence INT NOT NULL DEFAULT 0;

ALTER TABLE cpe_product_aliases
    ADD COLUMN IF NOT EXISTS evidence_url VARCHAR(1024);

ALTER TABLE cpe_product_aliases
    ADD COLUMN IF NOT EXISTS review_state VARCHAR(16) NOT NULL DEFAULT 'MANUAL';

CREATE INDEX IF NOT EXISTS idx_cpe_product_aliases_review_state ON cpe_product_aliases(review_state);
CREATE INDEX IF NOT EXISTS idx_cpe_product_aliases_source       ON cpe_product_aliases(source);
CREATE INDEX IF NOT EXISTS idx_cpe_product_aliases_vendor_id    ON cpe_product_aliases(cpe_vendor_id);

-- =========================================================
-- Security / users / roles
-- =========================================================

CREATE TABLE IF NOT EXISTS app_users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
    password_change_required BOOLEAN NOT NULL DEFAULT FALSE,
    bootstrap_admin BOOLEAN NOT NULL DEFAULT FALSE,

    failed_login_count INT NOT NULL DEFAULT 0,
    last_failed_login_at TIMESTAMP NULL,
    locked_at TIMESTAMP NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_app_users_username UNIQUE (username)
    );

CREATE INDEX IF NOT EXISTS idx_app_users_username ON app_users(username);

CREATE TABLE IF NOT EXISTS app_roles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_app_roles_name UNIQUE (role_name)
    );

CREATE INDEX IF NOT EXISTS idx_app_roles_name ON app_roles(role_name);

CREATE TABLE IF NOT EXISTS app_user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_app_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_app_user_roles_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_app_user_roles_role FOREIGN KEY (role_id) REFERENCES app_roles(id)
    );

CREATE INDEX IF NOT EXISTS idx_app_user_roles_user ON app_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_app_user_roles_role ON app_user_roles(role_id);

CREATE TABLE IF NOT EXISTS security_audit_logs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    actor_username VARCHAR(100),
    target_username VARCHAR(100),
    result VARCHAR(32) NOT NULL,
    ip_address VARCHAR(128),
    message CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_security_audit_logs_created_at
    ON security_audit_logs(created_at);

CREATE INDEX IF NOT EXISTS idx_security_audit_logs_event_type
    ON security_audit_logs(event_type);

CREATE INDEX IF NOT EXISTS idx_security_audit_logs_actor_username
    ON security_audit_logs(actor_username);

CREATE INDEX IF NOT EXISTS idx_security_audit_logs_target_username
    ON security_audit_logs(target_username);

MERGE INTO app_roles (role_name) KEY (role_name) VALUES ('ADMIN');
MERGE INTO app_roles (role_name) KEY (role_name) VALUES ('OPERATOR');
MERGE INTO app_roles (role_name) KEY (role_name) VALUES ('VIEWER');

-- =========================================================
-- System settings
-- =========================================================

CREATE TABLE IF NOT EXISTS system_settings
(
    setting_key VARCHAR(128) PRIMARY KEY,
    setting_value VARCHAR(2048) NOT NULL,
    updated_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_system_settings_updated_at
    ON system_settings(updated_at);