-- =========================================================
-- schema.sql (H2) - Normal use (IF NOT EXISTS)
-- DB is usually retained; drop manually when needed.
-- =========================================================

-- =========================================================
-- Assets
-- =========================================================

CREATE TABLE IF NOT EXISTS assets
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key VARCHAR(128),
    name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(32),
    owner VARCHAR(255),
    note CLOB,

    -- inventory ingestion (osquery/fleet/wazuh/manual)
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    -- optional: platform hint (windows/linux/darwin)
    platform VARCHAR(32),
    -- optional: OS display hint (free-form)
    os_version VARCHAR(128),

    -- ===== Added: identity / hardware / OS details (osquery-friendly) =====
    system_uuid VARCHAR(128),
    serial_number VARCHAR(128),

    hardware_vendor VARCHAR(255),
    hardware_model VARCHAR(255),

    computer_name VARCHAR(255),
    local_hostname VARCHAR(255),

    cpu_brand VARCHAR(255),
    cpu_physical_cores INT,
    cpu_logical_cores INT,
    arch VARCHAR(64),

    os_name VARCHAR(128),
    os_build VARCHAR(128),
    os_major INT,
    os_minor INT,
    os_patch INT,

    -- snapshot observation timestamp
    last_seen_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_assets_external_key UNIQUE (external_key)
    );

-- NOTE: uq_assets_external_key がインデックスを持つため idx_assets_external_key は通常不要だが、
-- 既存互換のため残す/削除は運用判断（ここでは現状維持で残す場合はコメント解除）
CREATE INDEX IF NOT EXISTS idx_assets_external_key ON assets(external_key);
CREATE INDEX IF NOT EXISTS idx_assets_source ON assets(source);
CREATE INDEX IF NOT EXISTS idx_assets_last_seen ON assets(last_seen_at);

-- Added indexes (safe, optional but useful)
CREATE INDEX IF NOT EXISTS idx_assets_system_uuid ON assets(system_uuid);
CREATE INDEX IF NOT EXISTS idx_assets_serial_number ON assets(serial_number);
CREATE INDEX IF NOT EXISTS idx_assets_local_hostname ON assets(local_hostname);
CREATE INDEX IF NOT EXISTS idx_assets_platform ON assets(platform);

-- =========================================================
-- CPE Dictionary (vendors/products)
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_vendors
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_norm VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    source varchar(20) not null default 'CPE_DICT',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_cpe_vendors_name UNIQUE (name_norm)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_vendors_name ON cpe_vendors(name_norm);

CREATE TABLE IF NOT EXISTS cpe_products
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT NOT NULL,
    name_norm VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    source varchar(20) not null default 'CPE_DICT',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_cpe_products_vendor FOREIGN KEY (vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT uq_cpe_products_vendor_name UNIQUE (vendor_id, name_norm)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_products_vendor ON cpe_products(vendor_id);
CREATE INDEX IF NOT EXISTS idx_cpe_products_name ON cpe_products(name_norm);
CREATE INDEX IF NOT EXISTS idx_cpe_products_vendor_name ON cpe_products(vendor_id, name_norm);

-- =========================================================
-- CPE Feed sync state
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_name VARCHAR(64) NOT NULL,
    meta_sha256 VARCHAR(128),
    meta_last_modified VARCHAR(64),
    meta_size BIGINT,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_cpe_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_sync_state_feed ON cpe_sync_state(feed_name);

-- =========================================================
-- Import runs (inventory ingestion unit)
-- =========================================================

CREATE TABLE IF NOT EXISTS import_runs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- existing columns (used by current code)
    source VARCHAR(32) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    file_hash VARCHAR(128),
    summary CLOB,
    assets_upserted INT DEFAULT 0 NOT NULL,
    software_upserted INT DEFAULT 0 NOT NULL,
    unresolved_count INT DEFAULT 0 NOT NULL,
    error_count INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- extended columns
    status VARCHAR(16) NOT NULL DEFAULT 'IMPORTED',
    original_filename VARCHAR(255),
    sha256 VARCHAR(128),
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    invalid_rows INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1024),

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_import_runs_started ON import_runs(started_at);
CREATE INDEX IF NOT EXISTS idx_import_runs_source ON import_runs(source);
CREATE INDEX IF NOT EXISTS idx_import_runs_status ON import_runs(status);

-- =========================================================
-- Admin Runs (generic job run history)
-- =========================================================
CREATE TABLE IF NOT EXISTS admin_runs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_type VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,

    started_at TIMESTAMP(6) NOT NULL,
    finished_at TIMESTAMP(6),
    duration_ms BIGINT,

    params_json CLOB,
    result_json CLOB,
    error_message CLOB,

    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_admin_runs_started_at ON admin_runs (started_at);
CREATE INDEX IF NOT EXISTS idx_admin_runs_job_type   ON admin_runs (job_type);
CREATE INDEX IF NOT EXISTS idx_admin_runs_status     ON admin_runs (status);

-- =========================================================
-- Software inventory
-- =========================================================

CREATE TABLE IF NOT EXISTS software_installs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,

    type VARCHAR(32) NOT NULL DEFAULT 'APPLICATION',
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',

    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255),
    version_raw VARCHAR(128),

    vendor VARCHAR(255) NOT NULL DEFAULT '',
    product VARCHAR(255) NOT NULL,

    version VARCHAR(64) NOT NULL DEFAULT '',
    version_norm VARCHAR(128),

    cpe_name VARCHAR(512),

    normalized_vendor VARCHAR(255),
    normalized_product VARCHAR(255),

    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    last_seen_at TIMESTAMP,

    import_run_id BIGINT,

    install_location VARCHAR(1024),
    installed_at TIMESTAMP NULL,
    package_identifier VARCHAR(255),
    arch VARCHAR(64),

    source_type VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',

    publisher VARCHAR(255),
    bundle_id VARCHAR(255),
    package_manager VARCHAR(64),
    install_source VARCHAR(64),

    edition VARCHAR(128),
    channel VARCHAR(64),
    release_label VARCHAR(128),

    purl VARCHAR(512),

    canonical_link_disabled BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_sw_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT fk_sw_cpe_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_sw_cpe_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id),
    CONSTRAINT fk_sw_import_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id),

    CONSTRAINT uq_sw_asset_vendor_product_version UNIQUE (asset_id, vendor, product, version)
    );

CREATE INDEX IF NOT EXISTS idx_sw_asset_id ON software_installs(asset_id);
CREATE INDEX IF NOT EXISTS idx_sw_cpe ON software_installs(cpe_name);
CREATE INDEX IF NOT EXISTS idx_sw_norm ON software_installs(normalized_vendor, normalized_product);
CREATE INDEX IF NOT EXISTS idx_sw_type ON software_installs(type);
CREATE INDEX IF NOT EXISTS idx_sw_source ON software_installs(source);
CREATE INDEX IF NOT EXISTS idx_sw_source_type ON software_installs(source_type);
CREATE INDEX IF NOT EXISTS idx_sw_last_seen ON software_installs(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_sw_import_run ON software_installs(import_run_id);

-- Added indexes (safe)
CREATE INDEX IF NOT EXISTS idx_sw_pkg_identifier ON software_installs(package_identifier);
CREATE INDEX IF NOT EXISTS idx_sw_publisher ON software_installs(publisher);
CREATE INDEX IF NOT EXISTS idx_sw_bundle_id ON software_installs(bundle_id);
CREATE INDEX IF NOT EXISTS idx_sw_pkg_manager ON software_installs(package_manager);
CREATE INDEX IF NOT EXISTS idx_sw_purl ON software_installs(purl);

-- Matching accelerators (DICT_ID is the primary path)
CREATE INDEX IF NOT EXISTS idx_sw_vendor_product_id
    ON software_installs(cpe_vendor_id, cpe_product_id);

CREATE INDEX IF NOT EXISTS idx_sw_asset_vendor_product_id
    ON software_installs(asset_id, cpe_vendor_id, cpe_product_id);

-- =========================================================
-- Staging tables for JSON Import (Upload -> Preview -> Import)
-- =========================================================

CREATE TABLE IF NOT EXISTS import_staging_assets
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_run_id BIGINT NOT NULL,
    row_no INT NOT NULL,

    external_key VARCHAR(128),
    name VARCHAR(255),
    asset_type VARCHAR(32),
    owner VARCHAR(255),
    note CLOB,

    source VARCHAR(32),
    platform VARCHAR(32),
    os_version VARCHAR(128),

    system_uuid VARCHAR(128),
    serial_number VARCHAR(128),

    hardware_vendor VARCHAR(255),
    hardware_model VARCHAR(255),

    computer_name VARCHAR(255),
    local_hostname VARCHAR(255),

    cpu_brand VARCHAR(255),
    cpu_physical_cores INT,
    cpu_logical_cores INT,
    arch VARCHAR(64),

    os_name VARCHAR(128),
    os_build VARCHAR(128),
    os_major INT,
    os_minor INT,
    os_patch INT,

    last_seen_at TIMESTAMP,

    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    validation_error VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_stage_assets_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id)
    );

CREATE INDEX IF NOT EXISTS idx_stage_assets_run ON import_staging_assets(import_run_id);
CREATE INDEX IF NOT EXISTS idx_stage_assets_key ON import_staging_assets(external_key);

CREATE TABLE IF NOT EXISTS import_staging_software
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_run_id BIGINT NOT NULL,
    row_no INT NOT NULL,

    external_key VARCHAR(128),

    vendor VARCHAR(255),
    product VARCHAR(255),
    version VARCHAR(64),

    install_location VARCHAR(1024),
    installed_at TIMESTAMP NULL,
    package_identifier VARCHAR(255),
    arch VARCHAR(64),

    source_type VARCHAR(64) NOT NULL DEFAULT 'JSON_UPLOAD',

    last_seen_at TIMESTAMP,

    type VARCHAR(32),
    source VARCHAR(32),

    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255),
    version_raw VARCHAR(128),

    publisher VARCHAR(255),
    bundle_id VARCHAR(255),
    package_manager VARCHAR(64),
    install_source VARCHAR(64),

    edition VARCHAR(128),
    channel VARCHAR(64),
    release_label VARCHAR(128),

    purl VARCHAR(512),

    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    validation_error VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_stage_sw_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id)
    );

CREATE INDEX IF NOT EXISTS idx_stage_sw_run ON import_staging_software(import_run_id);
CREATE INDEX IF NOT EXISTS idx_stage_sw_key ON import_staging_software(external_key);
CREATE INDEX IF NOT EXISTS idx_stage_sw_product ON import_staging_software(product);

-- =========================================================
-- Vulnerabilities (CVE)
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerabilities
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source VARCHAR(32) NOT NULL DEFAULT 'NVD',
    external_id VARCHAR(64) NOT NULL,

    title VARCHAR(1024),
    description CLOB,

    severity VARCHAR(16),
    cvss_version VARCHAR(16),
    cvss_score DOUBLE,

    published_at TIMESTAMP,
    last_modified_at TIMESTAMP,

    -- ==============================
    -- KEV metadata
    -- ==============================
    kev_flag BOOLEAN DEFAULT FALSE NOT NULL,
    kev_date_added DATE,
    kev_due_date DATE,
    kev_ransomware_use VARCHAR(16),
    kev_updated_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_vuln_source_external UNIQUE (source, external_id)
    );

CREATE INDEX IF NOT EXISTS idx_vuln_severity ON vulnerabilities(severity);
CREATE INDEX IF NOT EXISTS idx_vuln_lastmod_id ON vulnerabilities(last_modified_at, id);
CREATE INDEX IF NOT EXISTS idx_vuln_kev_flag ON vulnerabilities(kev_flag);

-- =========================================================
-- KEV sync state
-- =========================================================
CREATE TABLE IF NOT EXISTS kev_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    feed_name VARCHAR(64) NOT NULL,
    etag VARCHAR(255),
    last_modified VARCHAR(128),
    body_sha256 VARCHAR(128),
    body_size BIGINT,
    fetched_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_kev_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_kev_sync_state_feed ON kev_sync_state(feed_name);

-- =========================================================
-- Vulnerability affected CPEs
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerability_affected_cpes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vulnerability_id BIGINT NOT NULL,

    cpe_name VARCHAR(512) NOT NULL,

    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    vendor_norm VARCHAR(255),
    product_norm VARCHAR(255),

    -- version range: NULLは使わず未指定は "" で運用
    version_start_including VARCHAR(255) NOT NULL DEFAULT '',
    version_start_excluding VARCHAR(255) NOT NULL DEFAULT '',
    version_end_including   VARCHAR(255) NOT NULL DEFAULT '',
    version_end_excluding   VARCHAR(255) NOT NULL DEFAULT '',

    -- 追加: 安定dedupe用
    dedupe_key CHAR(64),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_vac_vuln
    FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),

    CONSTRAINT fk_vac_cpe_vendor
    FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),

    CONSTRAINT fk_vac_cpe_product
    FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id),

    -- 既存互換の複合UNIQUEは維持
    CONSTRAINT uq_vac_dedupe UNIQUE (
                                        vulnerability_id,
                                        cpe_name,
                                        version_start_including,
                                        version_start_excluding,
                                        version_end_including,
                                        version_end_excluding
                                    )
    );

CREATE INDEX IF NOT EXISTS idx_vac_cpe
    ON vulnerability_affected_cpes(cpe_name);

CREATE INDEX IF NOT EXISTS idx_vac_vuln
    ON vulnerability_affected_cpes(vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_id
    ON vulnerability_affected_cpes(cpe_vendor_id, cpe_product_id);

CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_norm
    ON vulnerability_affected_cpes(vendor_norm, product_norm);

-- 追加: dedupe_key unique index
CREATE UNIQUE INDEX IF NOT EXISTS uq_vac_dedupe_key
    ON vulnerability_affected_cpes(dedupe_key);

-- =========================================================
-- Alerts
-- =========================================================

CREATE TABLE IF NOT EXISTS alerts
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    software_install_id BIGINT,
    vulnerability_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL,
    certainty VARCHAR(16) NOT NULL DEFAULT 'CONFIRMED',
    uncertain_reason VARCHAR(64),
    matched_by VARCHAR(32),

    close_reason VARCHAR(255),
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,

    snapshot_asset_id BIGINT,
    snapshot_asset_name VARCHAR(255),
    snapshot_external_key VARCHAR(128),
    snapshot_software_install_id BIGINT,
    snapshot_vendor VARCHAR(255),
    snapshot_product VARCHAR(255),
    snapshot_version VARCHAR(64),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_alert_sw FOREIGN KEY (software_install_id) REFERENCES software_installs(id),
    CONSTRAINT fk_alert_vuln FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),
    CONSTRAINT uq_alert_pair UNIQUE (software_install_id, vulnerability_id)
    );

CREATE INDEX IF NOT EXISTS idx_alert_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alert_certainty ON alerts(certainty);
CREATE INDEX IF NOT EXISTS idx_alert_vuln ON alerts(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_alert_sw ON alerts(software_install_id);
CREATE INDEX IF NOT EXISTS idx_alert_status_certainty ON alerts(status, certainty);
CREATE INDEX IF NOT EXISTS idx_alert_vuln_status ON alerts(vulnerability_id, status);

-- =========================================================
-- CVE feed sync state (NVD CVE JSON 2.0 feeds)
-- =========================================================

CREATE TABLE IF NOT EXISTS cve_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    feed_name VARCHAR(64) NOT NULL,

    meta_sha256 VARCHAR(128),
    meta_last_modified VARCHAR(64),
    meta_size BIGINT,

    last_synced_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_cve_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_cve_sync_state_feed ON cve_sync_state(feed_name);

-- =========================================================
-- Unresolved mappings (dictionary training queue)
-- =========================================================

CREATE TABLE IF NOT EXISTS unresolved_mappings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source VARCHAR(32) NOT NULL,

    vendor_raw VARCHAR(255) NOT NULL,
    product_raw VARCHAR(255) NOT NULL,
    version_raw VARCHAR(128),

    normalized_vendor VARCHAR(255),
    normalized_product VARCHAR(255),

    candidate_vendor_ids VARCHAR(512),
    candidate_product_ids VARCHAR(512),

    status VARCHAR(16) NOT NULL DEFAULT 'NEW',
    note VARCHAR(1024),

    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uk_um_vendor_product UNIQUE (vendor_raw, product_raw)
    );

CREATE INDEX IF NOT EXISTS idx_um_status ON unresolved_mappings(status);
CREATE INDEX IF NOT EXISTS idx_um_norm ON unresolved_mappings(normalized_vendor, normalized_product);
CREATE INDEX IF NOT EXISTS idx_um_vendor_product ON unresolved_mappings(vendor_raw, product_raw);

-- =========================================================
-- Synonyms / Aliases (dictionary learning)  [ID-based]
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_vendor_aliases
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    alias_norm VARCHAR(255) NOT NULL,

    cpe_vendor_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    note VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_vendor_alias_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT uq_vendor_alias UNIQUE (alias_norm)
    );

CREATE INDEX IF NOT EXISTS idx_vendor_alias_vendor ON cpe_vendor_aliases(cpe_vendor_id);
CREATE INDEX IF NOT EXISTS idx_vendor_alias_status ON cpe_vendor_aliases(status);

CREATE TABLE IF NOT EXISTS cpe_product_aliases
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cpe_vendor_id BIGINT NOT NULL,

    alias_norm VARCHAR(255) NOT NULL,

    cpe_product_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    note VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_product_alias_vendor  FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_product_alias_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id),
    CONSTRAINT uq_product_alias UNIQUE (cpe_vendor_id, alias_norm)
    );

CREATE INDEX IF NOT EXISTS idx_product_alias_vendor ON cpe_product_aliases(cpe_vendor_id);
CREATE INDEX IF NOT EXISTS idx_product_alias_product ON cpe_product_aliases(cpe_product_id);
CREATE INDEX IF NOT EXISTS idx_product_alias_status ON cpe_product_aliases(status);

-- =========================================================
-- Alias metadata extension (Top20 auto-seeding)
-- =========================================================

-- ---------- cpe_vendor_aliases ----------
ALTER TABLE cpe_vendor_aliases
    ADD COLUMN IF NOT EXISTS source VARCHAR(32) NOT NULL DEFAULT 'MANUAL';

ALTER TABLE cpe_vendor_aliases
    ADD COLUMN IF NOT EXISTS confidence INT NOT NULL DEFAULT 0;

ALTER TABLE cpe_vendor_aliases
    ADD COLUMN IF NOT EXISTS evidence_url VARCHAR(1024);

ALTER TABLE cpe_vendor_aliases
    ADD COLUMN IF NOT EXISTS review_state VARCHAR(16) NOT NULL DEFAULT 'MANUAL';

CREATE INDEX IF NOT EXISTS idx_cpe_vendor_aliases_review_state ON cpe_vendor_aliases(review_state);
CREATE INDEX IF NOT EXISTS idx_cpe_vendor_aliases_source       ON cpe_vendor_aliases(source);

-- ---------- cpe_product_aliases ----------
ALTER TABLE cpe_product_aliases
    ADD COLUMN IF NOT EXISTS source VARCHAR(32) NOT NULL DEFAULT 'MANUAL';

ALTER TABLE cpe_product_aliases
    ADD COLUMN IF NOT EXISTS confidence INT NOT NULL DEFAULT 0;

ALTER TABLE cpe_product_aliases
    ADD COLUMN IF NOT EXISTS evidence_url VARCHAR(1024);

ALTER TABLE cpe_product_aliases
    ADD COLUMN IF NOT EXISTS review_state VARCHAR(16) NOT NULL DEFAULT 'MANUAL';

CREATE INDEX IF NOT EXISTS idx_cpe_product_aliases_review_state ON cpe_product_aliases(review_state);
CREATE INDEX IF NOT EXISTS idx_cpe_product_aliases_source       ON cpe_product_aliases(source);
CREATE INDEX IF NOT EXISTS idx_cpe_product_aliases_vendor_id    ON cpe_product_aliases(cpe_vendor_id);