-- =========================================================
-- schema.sql (H2) - Normal use (IF NOT EXISTS)
-- DB is usually retained; drop manually when needed.
-- =========================================================

-- =========================================================
-- Assets
-- =========================================================

CREATE TABLE IF NOT EXISTS assets
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key VARCHAR(128),
    name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(32),
    owner VARCHAR(255),
    note CLOB,

    -- inventory ingestion (osquery/fleet/wazuh/manual)
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    -- optional: platform hint (windows/linux/darwin)
    platform VARCHAR(32),
    -- optional: OS display hint (free-form)
    os_version VARCHAR(128),

    -- ===== Added: identity / hardware / OS details (osquery-friendly) =====
    system_uuid VARCHAR(128),
    serial_number VARCHAR(128),

    hardware_vendor VARCHAR(255),
    hardware_model VARCHAR(255),

    computer_name VARCHAR(255),
    local_hostname VARCHAR(255),

    cpu_brand VARCHAR(255),
    cpu_physical_cores INT,
    cpu_logical_cores INT,
    arch VARCHAR(64),

    os_name VARCHAR(128),
    os_build VARCHAR(128),
    os_major INT,
    os_minor INT,
    os_patch INT,

    -- snapshot observation timestamp
    last_seen_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_assets_external_key UNIQUE (external_key)
    );

CREATE INDEX IF NOT EXISTS idx_assets_external_key ON assets(external_key);
CREATE INDEX IF NOT EXISTS idx_assets_source ON assets(source);
CREATE INDEX IF NOT EXISTS idx_assets_last_seen ON assets(last_seen_at);

-- Added indexes (safe, optional but useful)
CREATE INDEX IF NOT EXISTS idx_assets_system_uuid ON assets(system_uuid);
CREATE INDEX IF NOT EXISTS idx_assets_serial_number ON assets(serial_number);
CREATE INDEX IF NOT EXISTS idx_assets_local_hostname ON assets(local_hostname);
CREATE INDEX IF NOT EXISTS idx_assets_platform ON assets(platform);

-- =========================================================
-- CPE Dictionary (vendors/products)
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_vendors
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_norm VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_cpe_vendors_name UNIQUE (name_norm)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_vendors_name ON cpe_vendors(name_norm);

CREATE TABLE IF NOT EXISTS cpe_products
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT NOT NULL,
    name_norm VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_cpe_products_vendor FOREIGN KEY (vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT uq_cpe_products_vendor_name UNIQUE (vendor_id, name_norm)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_products_vendor ON cpe_products(vendor_id);
CREATE INDEX IF NOT EXISTS idx_cpe_products_name ON cpe_products(name_norm);
CREATE INDEX IF NOT EXISTS idx_cpe_products_vendor_name ON cpe_products(vendor_id, name_norm);

-- =========================================================
-- CPE Feed sync state
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_name VARCHAR(64) NOT NULL,
    meta_sha256 VARCHAR(128),
    meta_last_modified VARCHAR(64),
    meta_size BIGINT,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_cpe_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_sync_state_feed ON cpe_sync_state(feed_name);

-- =========================================================
-- Import runs (inventory ingestion unit)
-- 既存互換: source/kind/started_at/... を維持
-- 拡張: JSON Upload → Preview → Import を支える列を追加（既存コードを壊さないため DEFAULT を付与）
-- =========================================================

CREATE TABLE IF NOT EXISTS import_runs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- existing columns (used by current code)
    source VARCHAR(32) NOT NULL,          -- OSQUERY/FLEET/WAZUH/MANUAL/...
    kind VARCHAR(32) NOT NULL,            -- INVENTORY/OSQUERY_JSON/CSV/... (既存)
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    file_hash VARCHAR(128),
    summary CLOB,
    assets_upserted INT DEFAULT 0 NOT NULL,
    software_upserted INT DEFAULT 0 NOT NULL,
    unresolved_count INT DEFAULT 0 NOT NULL,
    error_count INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- extended columns (for staged import; safe defaults)
    status VARCHAR(16) NOT NULL DEFAULT 'IMPORTED',      -- STAGED/IMPORTED/FAILED (既存Insert互換のためDEFAULT)
    original_filename VARCHAR(255),
    sha256 VARCHAR(128),
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    invalid_rows INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1024),

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_import_runs_started ON import_runs(started_at);
CREATE INDEX IF NOT EXISTS idx_import_runs_source ON import_runs(source);
CREATE INDEX IF NOT EXISTS idx_import_runs_status ON import_runs(status);

-- =========================================================
-- Software inventory
-- 既存構造を維持しつつ、今回の拡張カラムを追加
-- =========================================================

CREATE TABLE IF NOT EXISTS software_installs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,

    -- APPLICATION / OPERATING_SYSTEM
    type VARCHAR(32) NOT NULL DEFAULT 'APPLICATION',
    -- inventory source (osquery/fleet/wazuh/manual) 既存
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',

    -- raw input values (for troubleshooting & dictionary training)
    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255),
    version_raw VARCHAR(128),

    vendor VARCHAR(255) NOT NULL DEFAULT '',
    product VARCHAR(255) NOT NULL,

    -- NOTE: 既存ロジック互換のため、DBは現行通り（空文字運用でもOK）に保持。
    version VARCHAR(64) NOT NULL DEFAULT '',
    -- normalized version string (idempotency; not for numeric comparison yet)
    version_norm VARCHAR(128),

    cpe_name VARCHAR(512),

    normalized_vendor VARCHAR(255),
    normalized_product VARCHAR(255),

    -- canonical dictionary linkage
    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    -- snapshot observation timestamp
    last_seen_at TIMESTAMP,

    -- trace which import run produced/updated this row
    import_run_id BIGINT,

    -- existing extended columns
    install_location VARCHAR(1024),
    installed_at TIMESTAMP NULL,
    package_identifier VARCHAR(255),
    arch VARCHAR(64),

    -- source_type: data origin management (FLEET / JSON etc.)
    -- 既存の source と併存させる（既存コード互換）
    source_type VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',

    -- ===== Added: higher-precision identifiers / provenance =====
    publisher VARCHAR(255),
    bundle_id VARCHAR(255),
    package_manager VARCHAR(64),
    install_source VARCHAR(64),

    edition VARCHAR(128),
    channel VARCHAR(64),
    release VARCHAR(128),

    purl VARCHAR(512),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_sw_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT fk_sw_cpe_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_sw_cpe_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id),
    CONSTRAINT fk_sw_import_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id),

    CONSTRAINT uq_sw_asset_vendor_product_version UNIQUE (asset_id, vendor, product, version)
    );

CREATE INDEX IF NOT EXISTS idx_sw_asset_id ON software_installs(asset_id);
CREATE INDEX IF NOT EXISTS idx_sw_cpe ON software_installs(cpe_name);
CREATE INDEX IF NOT EXISTS idx_sw_norm ON software_installs(normalized_vendor, normalized_product);
CREATE INDEX IF NOT EXISTS idx_sw_type ON software_installs(type);
CREATE INDEX IF NOT EXISTS idx_sw_source ON software_installs(source);
CREATE INDEX IF NOT EXISTS idx_sw_source_type ON software_installs(source_type);
CREATE INDEX IF NOT EXISTS idx_sw_last_seen ON software_installs(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_sw_import_run ON software_installs(import_run_id);

-- Added indexes (safe)
CREATE INDEX IF NOT EXISTS idx_sw_pkg_identifier ON software_installs(package_identifier);
CREATE INDEX IF NOT EXISTS idx_sw_publisher ON software_installs(publisher);
CREATE INDEX IF NOT EXISTS idx_sw_bundle_id ON software_installs(bundle_id);
CREATE INDEX IF NOT EXISTS idx_sw_pkg_manager ON software_installs(package_manager);
CREATE INDEX IF NOT EXISTS idx_sw_purl ON software_installs(purl);

-- =========================================================
-- Matching accelerators (DICT_ID is the primary path)
-- =========================================================
CREATE INDEX IF NOT EXISTS idx_sw_vendor_product_id
    ON software_installs(cpe_vendor_id, cpe_product_id);

CREATE INDEX IF NOT EXISTS idx_sw_asset_vendor_product_id
    ON software_installs(asset_id, cpe_vendor_id, cpe_product_id);

-- =========================================================
-- Staging tables for JSON Import (Upload -> Preview -> Import)
-- import_runs.id を参照して Preview/Import の2段階を実現
-- =========================================================

CREATE TABLE IF NOT EXISTS import_staging_assets
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_run_id BIGINT NOT NULL,
    row_no INT NOT NULL,

    external_key VARCHAR(128),
    name VARCHAR(255),
    asset_type VARCHAR(32),
    owner VARCHAR(255),
    note CLOB,

    -- Added: staging for expanded asset fields
    source VARCHAR(32),
    platform VARCHAR(32),
    os_version VARCHAR(128),

    system_uuid VARCHAR(128),
    serial_number VARCHAR(128),

    hardware_vendor VARCHAR(255),
    hardware_model VARCHAR(255),

    computer_name VARCHAR(255),
    local_hostname VARCHAR(255),

    cpu_brand VARCHAR(255),
    cpu_physical_cores INT,
    cpu_logical_cores INT,
    arch VARCHAR(64),

    os_name VARCHAR(128),
    os_build VARCHAR(128),
    os_major INT,
    os_minor INT,
    os_patch INT,

    last_seen_at TIMESTAMP,

    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    validation_error VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_stage_assets_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id)
    );

CREATE INDEX IF NOT EXISTS idx_stage_assets_run ON import_staging_assets(import_run_id);
CREATE INDEX IF NOT EXISTS idx_stage_assets_key ON import_staging_assets(external_key);

CREATE TABLE IF NOT EXISTS import_staging_software
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_run_id BIGINT NOT NULL,
    row_no INT NOT NULL,

    external_key VARCHAR(128),     -- assets.external_key と紐付け前提

    vendor VARCHAR(255),
    product VARCHAR(255),
    version VARCHAR(64),

    install_location VARCHAR(1024),
    installed_at TIMESTAMP NULL,
    package_identifier VARCHAR(255),
    arch VARCHAR(64),

    source_type VARCHAR(64) NOT NULL DEFAULT 'JSON_UPLOAD',

    -- snapshot observation timestamp (import時刻など)
    last_seen_at TIMESTAMP,

    -- Added: staging fields for better precision
    type VARCHAR(32),
    source VARCHAR(32),

    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255),
    version_raw VARCHAR(128),

    publisher VARCHAR(255),
    bundle_id VARCHAR(255),
    package_manager VARCHAR(64),
    install_source VARCHAR(64),

    edition VARCHAR(128),
    channel VARCHAR(64),
    release VARCHAR(128),

    purl VARCHAR(512),

    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    validation_error VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_stage_sw_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id)
    );

CREATE INDEX IF NOT EXISTS idx_stage_sw_run ON import_staging_software(import_run_id);
CREATE INDEX IF NOT EXISTS idx_stage_sw_key ON import_staging_software(external_key);
CREATE INDEX IF NOT EXISTS idx_stage_sw_product ON import_staging_software(product);

-- =========================================================
-- Vulnerabilities (CVE)
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerabilities
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- entity references this column
    source VARCHAR(32) NOT NULL DEFAULT 'NVD',

    external_id VARCHAR(64) NOT NULL,
    title VARCHAR(1024),
    -- entity references this column
    description CLOB,

    severity VARCHAR(16),
    cvss_version VARCHAR(16),
    cvss_score DOUBLE,

    published_at TIMESTAMP,
    last_modified_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_vuln_external_id UNIQUE (external_id)
    );

CREATE INDEX IF NOT EXISTS idx_vuln_external_id ON vulnerabilities(external_id);
CREATE INDEX IF NOT EXISTS idx_vuln_severity ON vulnerabilities(severity);

-- =========================================================
-- Vulnerability affected CPEs
-- 設計方針:
-- - *_nn 列は廃止
-- - version range 4列は NOT NULL + DEFAULT ''（NULLを使わない）
-- - dedupe は本体6列（vuln_id + cpe_name + range4）で UNIQUE
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerability_affected_cpes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vulnerability_id BIGINT NOT NULL,

    -- NVD criteria (CPE 2.3 URI)
    cpe_name VARCHAR(512) NOT NULL,

    -- optional (dictionary linkage)
    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    -- optional (normalized fallback)
    vendor_norm VARCHAR(255),
    product_norm VARCHAR(255),

    -- version range: never NULL, empty string means "unspecified"
    version_start_including VARCHAR(255) NOT NULL DEFAULT '',
    version_start_excluding VARCHAR(255) NOT NULL DEFAULT '',
    version_end_including   VARCHAR(255) NOT NULL DEFAULT '',
    version_end_excluding   VARCHAR(255) NOT NULL DEFAULT '',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_vac_vuln       FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),
    CONSTRAINT fk_vac_cpe_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_vac_cpe_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id)
    );

-- dedupe key（6列、本体列）
CREATE UNIQUE INDEX IF NOT EXISTS ux_vac_dedupe
    ON vulnerability_affected_cpes (
    vulnerability_id,
    cpe_name,
    version_start_including,
    version_start_excluding,
    version_end_including,
    version_end_excluding
    );

-- search indexes
CREATE INDEX IF NOT EXISTS idx_vac_cpe ON vulnerability_affected_cpes(cpe_name);
CREATE INDEX IF NOT EXISTS idx_vac_vuln ON vulnerability_affected_cpes(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_id ON vulnerability_affected_cpes(cpe_vendor_id, cpe_product_id);
CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_norm ON vulnerability_affected_cpes(vendor_norm, product_norm);

-- =========================================================
-- Alerts
-- =========================================================

CREATE TABLE IF NOT EXISTS alerts
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    software_install_id BIGINT NOT NULL,
    vulnerability_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL,
    certainty VARCHAR(16) NOT NULL DEFAULT 'CONFIRMED',
    uncertain_reason VARCHAR(64),
    matched_by VARCHAR(32),

    close_reason VARCHAR(255),
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_alert_sw FOREIGN KEY (software_install_id) REFERENCES software_installs(id),
    CONSTRAINT fk_alert_vuln FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),
    CONSTRAINT uq_alert_pair UNIQUE (software_install_id, vulnerability_id)
    );

CREATE INDEX IF NOT EXISTS idx_alert_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alert_certainty ON alerts(certainty);
CREATE INDEX IF NOT EXISTS idx_alert_vuln ON alerts(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_alert_sw ON alerts(software_install_id);
CREATE INDEX IF NOT EXISTS idx_alert_status_certainty ON alerts(status, certainty);

-- =========================================================
-- CVE feed sync state (NVD CVE JSON 2.0 feeds)
-- =========================================================

CREATE TABLE IF NOT EXISTS cve_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    feed_name VARCHAR(64) NOT NULL,

    meta_sha256 VARCHAR(128),
    meta_last_modified VARCHAR(64),
    meta_size BIGINT,

    last_synced_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_cve_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_cve_sync_state_feed ON cve_sync_state(feed_name);

-- =========================================================
-- Unresolved mappings (dictionary training queue)
-- =========================================================

CREATE TABLE IF NOT EXISTS unresolved_mappings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source VARCHAR(32) NOT NULL,

    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255) NOT NULL,
    version_raw VARCHAR(128),

    normalized_vendor VARCHAR(255),
    normalized_product VARCHAR(255),

    candidate_vendor_ids VARCHAR(512),
    candidate_product_ids VARCHAR(512),

    status VARCHAR(16) NOT NULL DEFAULT 'NEW', -- NEW/RESOLVED/IGNORED
    note VARCHAR(1024),

    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_um_status ON unresolved_mappings(status);
CREATE INDEX IF NOT EXISTS idx_um_norm ON unresolved_mappings(normalized_vendor, normalized_product);
CREATE INDEX IF NOT EXISTS idx_um_source ON unresolved_mappings(source);

-- =========================================================
-- Synonyms / Aliases (dictionary learning)  [ID-based]
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_vendor_aliases
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- normalized alias key (must be normalized by the app)
    alias_norm VARCHAR(255) NOT NULL,

    -- canonical dictionary id
    cpe_vendor_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE/INACTIVE
    note VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_vendor_alias_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT uq_vendor_alias UNIQUE (alias_norm)
    );

CREATE INDEX IF NOT EXISTS idx_vendor_alias_vendor ON cpe_vendor_aliases(cpe_vendor_id);
CREATE INDEX IF NOT EXISTS idx_vendor_alias_status ON cpe_vendor_aliases(status);

CREATE TABLE IF NOT EXISTS cpe_product_aliases
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- vendor scope (avoid collisions)
    cpe_vendor_id BIGINT NOT NULL,

    alias_norm VARCHAR(255) NOT NULL,

    -- canonical dictionary id
    cpe_product_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE/INACTIVE
    note VARCHAR(1024),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_product_alias_vendor  FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_product_alias_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id),
    CONSTRAINT uq_product_alias UNIQUE (cpe_vendor_id, alias_norm)
    );

CREATE INDEX IF NOT EXISTS idx_product_alias_vendor ON cpe_product_aliases(cpe_vendor_id);
CREATE INDEX IF NOT EXISTS idx_product_alias_product ON cpe_product_aliases(cpe_product_id);
CREATE INDEX IF NOT EXISTS idx_product_alias_status ON cpe_product_aliases(status);