-- =========================================================
-- schema.sql (H2)
-- =========================================================

CREATE TABLE IF NOT EXISTS assets
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key VARCHAR(128),
    name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(32),
    owner VARCHAR(255),
    note CLOB,

    -- inventory ingestion (osquery/fleet/wazuh/manual)
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    -- optional: platform hint (windows/linux/darwin)
    platform VARCHAR(32),
    -- optional: OS display hint (free-form)
    os_version VARCHAR(128),
    -- snapshot observation timestamp
    last_seen_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_assets_external_key UNIQUE (external_key)
    );

CREATE INDEX IF NOT EXISTS idx_assets_external_key ON assets(external_key);
CREATE INDEX IF NOT EXISTS idx_assets_source ON assets(source);
CREATE INDEX IF NOT EXISTS idx_assets_last_seen ON assets(last_seen_at);

-- =========================================================
-- CPE Dictionary (vendors/products)
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_vendors
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_norm VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_cpe_vendors_name UNIQUE (name_norm)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_vendors_name ON cpe_vendors(name_norm);

CREATE TABLE IF NOT EXISTS cpe_products
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT NOT NULL,
    name_norm VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_cpe_products_vendor FOREIGN KEY (vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT uq_cpe_products_vendor_name UNIQUE (vendor_id, name_norm)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_products_vendor ON cpe_products(vendor_id);
CREATE INDEX IF NOT EXISTS idx_cpe_products_name ON cpe_products(name_norm);
CREATE INDEX IF NOT EXISTS idx_cpe_products_vendor_name ON cpe_products(vendor_id, name_norm);

-- =========================================================
-- CPE Feed sync state
-- =========================================================

CREATE TABLE IF NOT EXISTS cpe_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_name VARCHAR(64) NOT NULL,
    meta_sha256 VARCHAR(128),
    meta_last_modified VARCHAR(64),
    meta_size BIGINT,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_cpe_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_cpe_sync_state_feed ON cpe_sync_state(feed_name);

-- =========================================================
-- Import runs (inventory ingestion unit)
-- =========================================================

CREATE TABLE IF NOT EXISTS import_runs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source VARCHAR(32) NOT NULL,          -- OSQUERY/FLEET/WAZUH/MANUAL/...
    kind VARCHAR(32) NOT NULL,            -- INVENTORY/OSQUERY_JSON/CSV/...

    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,

    file_hash VARCHAR(128),
    summary CLOB,

    assets_upserted INT DEFAULT 0 NOT NULL,
    software_upserted INT DEFAULT 0 NOT NULL,
    unresolved_count INT DEFAULT 0 NOT NULL,
    error_count INT DEFAULT 0 NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_import_runs_started ON import_runs(started_at);
CREATE INDEX IF NOT EXISTS idx_import_runs_source ON import_runs(source);

-- =========================================================
-- Software inventory
-- =========================================================

CREATE TABLE IF NOT EXISTS software_installs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,

    -- APPLICATION / OPERATING_SYSTEM
    type VARCHAR(32) NOT NULL DEFAULT 'APPLICATION',
    -- inventory source (osquery/fleet/wazuh/manual)
    source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',

    -- raw input values (for troubleshooting & dictionary training)
    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255),
    version_raw VARCHAR(128),

    vendor VARCHAR(255) NOT NULL DEFAULT '',
    product VARCHAR(255) NOT NULL,
    version VARCHAR(64) NOT NULL DEFAULT '',
    -- normalized version string (idempotency; not for numeric comparison yet)
    version_norm VARCHAR(128),

    cpe_name VARCHAR(512),

    normalized_vendor VARCHAR(255),
    normalized_product VARCHAR(255),

    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    -- snapshot observation timestamp
    last_seen_at TIMESTAMP,
    -- trace which import run produced/updated this row
    import_run_id BIGINT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_sw_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT fk_sw_cpe_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_sw_cpe_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id),
    CONSTRAINT fk_sw_import_run FOREIGN KEY (import_run_id) REFERENCES import_runs(id),

    CONSTRAINT uq_sw_asset_vendor_product_version UNIQUE (asset_id, vendor, product, version)
    );

CREATE INDEX IF NOT EXISTS idx_sw_asset_id ON software_installs(asset_id);
CREATE INDEX IF NOT EXISTS idx_sw_cpe ON software_installs(cpe_name);
CREATE INDEX IF NOT EXISTS idx_sw_norm ON software_installs(normalized_vendor, normalized_product);
CREATE INDEX IF NOT EXISTS idx_sw_type ON software_installs(type);
CREATE INDEX IF NOT EXISTS idx_sw_source ON software_installs(source);
CREATE INDEX IF NOT EXISTS idx_sw_last_seen ON software_installs(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_sw_import_run ON software_installs(import_run_id);

-- =========================================================
-- Vulnerabilities (CVE)
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerabilities
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- entity references this column
    source VARCHAR(32) NOT NULL DEFAULT 'NVD',

    external_id VARCHAR(64) NOT NULL,
    title VARCHAR(1024),
    -- entity references this column
    description CLOB,

    severity VARCHAR(16),
    cvss_version VARCHAR(16),
    cvss_score DOUBLE,

    published_at TIMESTAMP,
    last_modified_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_vuln_external_id UNIQUE (external_id)
    );

CREATE INDEX IF NOT EXISTS idx_vuln_external_id ON vulnerabilities(external_id);
CREATE INDEX IF NOT EXISTS idx_vuln_severity ON vulnerabilities(severity);

-- =========================================================
-- Vulnerability affected CPEs
-- 重要: H2では UNIQUE 制約に NULL を含むと「NULL同士は別物」扱いになり、
--      同一に見える affected spec が重複 INSERT され得る。
-- 対策: NULL潰し用の *_nn 列（NOT NULL）を持ち、そこに UNIQUE を張る。
-- =========================================================

CREATE TABLE IF NOT EXISTS vulnerability_affected_cpes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vulnerability_id BIGINT NOT NULL,

    cpe_name VARCHAR(512),

    cpe_vendor_id BIGINT,
    cpe_product_id BIGINT,

    vendor_norm VARCHAR(255),
    product_norm VARCHAR(255),

    version_start_including VARCHAR(64),
    version_start_excluding VARCHAR(64),
    version_end_including VARCHAR(64),
    version_end_excluding VARCHAR(64),

    -- NULL潰し専用列（UNIQUEキー用）
    cpe_name_nn VARCHAR(512) NOT NULL DEFAULT '',
    cpe_vendor_id_nn BIGINT NOT NULL DEFAULT -1,
    cpe_product_id_nn BIGINT NOT NULL DEFAULT -1,
    vendor_norm_nn VARCHAR(255) NOT NULL DEFAULT '',
    product_norm_nn VARCHAR(255) NOT NULL DEFAULT '',
    version_start_including_nn VARCHAR(64) NOT NULL DEFAULT '',
    version_start_excluding_nn VARCHAR(64) NOT NULL DEFAULT '',
    version_end_including_nn VARCHAR(64) NOT NULL DEFAULT '',
    version_end_excluding_nn VARCHAR(64) NOT NULL DEFAULT '',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_vac_vuln FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),
    CONSTRAINT fk_vac_cpe_vendor FOREIGN KEY (cpe_vendor_id) REFERENCES cpe_vendors(id),
    CONSTRAINT fk_vac_cpe_product FOREIGN KEY (cpe_product_id) REFERENCES cpe_products(id)
    );

-- NULL潰し列で一意性を保証（重複INSERT防止）
CREATE UNIQUE INDEX IF NOT EXISTS ux_vac_dedupe
    ON vulnerability_affected_cpes(
    vulnerability_id,
    cpe_name_nn,
    cpe_vendor_id_nn,
    cpe_product_id_nn,
    vendor_norm_nn,
    product_norm_nn,
    version_start_including_nn,
    version_start_excluding_nn,
    version_end_including_nn,
    version_end_excluding_nn
    );

-- 検索用インデックス（既存列）
CREATE INDEX IF NOT EXISTS idx_vac_cpe ON vulnerability_affected_cpes(cpe_name);
CREATE INDEX IF NOT EXISTS idx_vac_vuln ON vulnerability_affected_cpes(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_id ON vulnerability_affected_cpes(cpe_vendor_id, cpe_product_id);
CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_norm ON vulnerability_affected_cpes(vendor_norm, product_norm);

-- （任意）NULL潰し列での検索が増えるならこちらも有効
CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_nn ON vulnerability_affected_cpes(cpe_vendor_id_nn, cpe_product_id_nn);
CREATE INDEX IF NOT EXISTS idx_vac_vendor_product_norm_nn ON vulnerability_affected_cpes(vendor_norm_nn, product_norm_nn);

-- =========================================================
-- Alerts
-- =========================================================

CREATE TABLE IF NOT EXISTS alerts
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    software_install_id BIGINT NOT NULL,
    vulnerability_id BIGINT NOT NULL,

    status VARCHAR(16) NOT NULL,
    certainty VARCHAR(16) NOT NULL DEFAULT 'CONFIRMED',
    uncertain_reason VARCHAR(64),
    matched_by VARCHAR(32),

    close_reason VARCHAR(255),
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_alert_sw FOREIGN KEY (software_install_id) REFERENCES software_installs(id),
    CONSTRAINT fk_alert_vuln FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities(id),
    CONSTRAINT uq_alert_pair UNIQUE (software_install_id, vulnerability_id)
    );

CREATE INDEX IF NOT EXISTS idx_alert_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alert_certainty ON alerts(certainty);
CREATE INDEX IF NOT EXISTS idx_alert_vuln ON alerts(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_alert_sw ON alerts(software_install_id);
CREATE INDEX IF NOT EXISTS idx_alert_status_certainty ON alerts(status, certainty);

-- =========================================================
-- CVE feed sync state (NVD CVE JSON 2.0 feeds)
-- =========================================================

CREATE TABLE IF NOT EXISTS cve_sync_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    feed_name VARCHAR(64) NOT NULL,

    meta_sha256 VARCHAR(128),
    meta_last_modified VARCHAR(64),
    meta_size BIGINT,

    last_synced_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_cve_sync_state_feed UNIQUE (feed_name)
    );

CREATE INDEX IF NOT EXISTS idx_cve_sync_state_feed ON cve_sync_state(feed_name);

-- =========================================================
-- Unresolved mappings (dictionary training queue)
-- =========================================================

CREATE TABLE IF NOT EXISTS unresolved_mappings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source VARCHAR(32) NOT NULL,

    vendor_raw VARCHAR(255),
    product_raw VARCHAR(255) NOT NULL,
    version_raw VARCHAR(128),

    normalized_vendor VARCHAR(255),
    normalized_product VARCHAR(255),

    candidate_vendor_ids VARCHAR(512),
    candidate_product_ids VARCHAR(512),

    status VARCHAR(16) NOT NULL DEFAULT 'NEW', -- NEW/RESOLVED/IGNORED
    note VARCHAR(1024),

    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_um_status ON unresolved_mappings(status);
CREATE INDEX IF NOT EXISTS idx_um_norm ON unresolved_mappings(normalized_vendor, normalized_product);
CREATE INDEX IF NOT EXISTS idx_um_source ON unresolved_mappings(source);